_merge: deep
theme: noesya-hugo-theme
params:
  plausible: www.noesya.coop
  ecosystem: www
  blocks:
    ignored:
      - block-class-organisation
  home:
    head:
      title: site
  design:
    force_full_width: true
  toc:
    disabled: true
  posts:
    single:
      meta:
        position: hero
        options:
          authors: false
          dates: false
          published_at: false
          reading_time: false
          share: false
          taxonomies: true
          updated_at: false
          with_labels: true
  projects:
    single:
      summary:
        position: content
      meta:
        position: none
  components:
    lightbox:
      disabled: false
      in_hero:
        disabled: true