[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/references/conseil/index.html"
to = "/projets/conseil/"

[[redirects]]
from = "/conseil/index.html"
to = "/metiers-1/conseil/"

[[redirects]]
from = "/references/2022-iut-bordeaux-montaigne/index.html"
to = "/projets/2022-iut-bordeaux-montaigne/"

[[redirects]]
from = "/references/applications/index.html"
to = "/projets/applications/"

[[redirects]]
from = "/references/2025-mmi-workshop/index.html"
to = "/projets/2025-mmi-workshop/"

[[redirects]]
from = "/references/index.html"
to = "/projets/"

[[redirects]]
from = "/references/2024-ecotheque/index.html"
to = "/projets/2024-ecotheque/"

[[redirects]]
from = "/actualites/2021-01-01-sebastien-gaya/index.html"
to = "/actualites/2021-09-01-sebastien-gaya/"

[[redirects]]
from = "/formation/index.html"
to = "/metiers-1/formation/"

[[redirects]]
from = "/references/2022-espeli/index.html"
to = "/projets/2022-espeli/"

[[redirects]]
from = "/references/2026-atelier-narration-interactive/index.html"
to = "/projets/2026-atelier-narration-interactive/"

[[redirects]]
from = "/organisations/marion-rebier/index.html"
to = "/organisations/beelearning/"

[[redirects]]
from = "/references/2021-osuny/index.html"
to = "/projets/2021-osuny/"

[[redirects]]
from = "/references/2026-gaite-lyrique/index.html"
to = "/projets/2026-gaite-lyrique/"

[[redirects]]
from = "/metiers/sites/index.html"
to = "/metiers-1/sites/"

[[redirects]]
from = "/metiers/formation/index.html"
to = "/metiers-1/formation/"

[[redirects]]
from = "/sites/index.html"
to = "/metiers-1/sites/"

[[redirects]]
from = "/references/2025-campus-art-mediterranee/index.html"
to = "/projets/2025-campus-art-mediterranee/"

[[redirects]]
from = "/organisations/academie-des-arts/index.html"
to = "/organisations/academie-des-beaux-arts/"

[[redirects]]
from = "/organisations/taltech/index.html"
to = "/organisations/tallinn-university-of-technology/"

[[redirects]]
from = "/metiers/conseil/index.html"
to = "/metiers-1/conseil/"

[[redirects]]
from = "/references/2022-extension-numecogestes/index.html"
to = "/projets/2022-extension-numecogestes/"

[[redirects]]
from = "/references/2026-fablab-a-lecole/index.html"
to = "/projets/2026-fablab-a-lecole/"

[[redirects]]
from = "/actualites/2021-09-01-olivia-simonet/index.html"
to = "/actualites/2022-09-01-olivia-simonet/"

[[redirects]]
from = "/references/2023-referentiel-de-competences-mmi/index.html"
to = "/projets/2023-referentiel-de-competences-mmi/"

[[redirects]]
from = "/organisations/mathieu-jahnich/index.html"
to = "/organisations/mj-conseil/"

[[redirects]]
from = "/references/2025-rennes-ville-et-metropole/index.html"
to = "/projets/2025-rennes-ville-et-metropole/"

[[redirects]]
from = "/references/sites/index.html"
to = "/projets/sites/"

[[redirects]]
from = "/equipe/index.html"
to = "/cooperative/"

[[redirects]]
from = "/references/2023-ecosysteme-de-la-mode/index.html"
to = "/projets/2023-ecosysteme-de-la-mode/"

[[redirects]]
from = "/references/2025-observatoire-citoyen-de-la-publicite/index.html"
to = "/projets/2025-observatoire-citoyen-de-la-publicite/"

[[redirects]]
from = "/metiers/applications/index.html"
to = "/metiers-1/applications/"

[[redirects]]
from = "/references/applicaitons/index.html"
to = "/projets/applications/"

[[redirects]]
from = "/applications/index.html"
to = "/metiers-1/applications/"

[[redirects]]
from = "/references/formation/index.html"
to = "/projets/formation/"

[[redirects]]
from = "/references/2021-ensemble-a-table/index.html"
to = "/projets/2021-ensemble-a-table/"

